name: github pages

on:
  push:
    branches:
      - master

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: select python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install sphinx==8.2.1 sphinx_rtd_theme==3.0.2

      - name: build documentation
        run: |
          source venv/bin/activate
          cd docs
          make html
          touch _build/html/.nojekyll

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html
